In [2]:
import pandas as pd

In [3]:
cars = pd.read_csv('cars.csv')

In [4]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevrolet s-10

In [5]:
cars.name.iloc[393]

'ford mustang gl'

In [6]:
cars['name'].iloc[393]

'ford mustang gl'

In [7]:
cars.iloc[100,:].cylinders

6

In [8]:
cars.name.iloc[200]

'ford granada ghia'

In [9]:
cars.iloc[-10:].loc[:,['mpg','horsepower','origin','name']]

      mpg  horsepower  origin                        name
388  26.0        92.0     usa  chrysler lebaron medallion
389  22.0       112.0     usa              ford granada l
390  32.0        96.0   japan            toyota celica gt
391  36.0        84.0     usa           dodge charger 2.2
392  27.0        90.0     usa            chevrolet camaro
393  27.0        86.0     usa             ford mustang gl
394  44.0        52.0  europe                   vw pickup
395  32.0        84.0     usa               dodge rampage
396  28.0        79.0     usa                 ford ranger
397  31.0        82.0     usa              chevrolet s-10

In [10]:
cars.tail(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
388,26.0,4,156.0,92.0,2585,14.5,82,usa,chrysler lebaron medallion
389,22.0,6,232.0,112.0,2835,14.7,82,usa,ford granada l
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
392,27.0,4,151.0,90.0,2950,17.3,82,usa,chevrolet camaro
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevrolet s-10

In [11]:
cars = pd.read_csv('cars.csv', index_col='name')

In [12]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
chevrolet s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [13]:
cars.index.sortlevel(ascending = False)

(Index(['vw type 3', 'vw super beetle', 'vw scirocco', 'vw rabbit l',
        'vw rabbit custom diesel', 'vw rabbit custom', 'vw rabbit custom',
        'vw rabbit c (diesel)', 'vw rabbit', 'vw rabbit',
        ...
        'amc gremlin', 'amc gremlin', 'amc concord dl 6', 'amc concord dl',
        'amc concord d/l', 'amc concord', 'amc concord', 'amc ambassador sst',
        'amc ambassador dpl', 'amc ambassador brougham'],
       dtype='object', name='name', length=398),
 array([ 59, 102, 278, 375, 244, 233, 293, 325, 175, 332, 309, 203, 197,
        394,  55, 353, 326, 142, 172, 240,  77,  19, 360, 275, 207, 179,
         76, 120, 335, 348, 343, 210, 123, 361,  82,  14, 318,  57, 267,
        171,  31, 144, 310, 235,  84,  53, 131, 205, 167, 382, 356, 321,
        270, 390, 108, 331, 239, 150, 346, 180, 122, 276,  22, 330, 218,
        354, 186,  79, 201, 234,  44, 252, 372, 308, 280, 370, 229, 116,
         47,  39, 156,   8,  63, 170, 208, 227, 256, 152,  97, 191, 135,
         75,  34,   2, 271, 338, 342, 302, 378, 350, 301, 158,  64,   7,
         41,  93, 163, 101,  15, 125, 105,  56, 344, 219,  11, 277, 359,
         78,  20, 209, 299, 178,  51, 118, 143, 183,  50, 106, 272, 307,
        124,  69, 222, 249, 300, 364, 387, 380, 281, 259, 251, 154,  90,
         67, 379, 287, 224, 113, 184,  49, 297, 211, 328, 111,  71, 334,
        243, 246, 294, 376, 377, 349, 322, 358, 319,  28, 355, 248, 181,
        329, 345, 384, 383, 149, 198, 279, 216, 337, 381,  36,   4, 232,
        396,  61,  80, 112,  32, 206, 168, 174, 130, 236, 166, 393, 336,
         48, 155, 126, 193,  17, 100, 286,  92, 159, 389, 365, 200, 228,
         74, 139, 136,  88, 190,  65,   5,  40, 264, 245, 373, 282, 255,
        254, 314,  25, 214, 351, 352,  43, 290, 104, 151, 304, 182, 117,
        147,  52, 148, 114, 288, 395, 269, 223,  42, 265, 250, 121,  27,
        215, 138,  89, 188, 238, 295,  58,  83, 185, 323, 146, 391,  10,
        199, 284, 316, 260, 340, 371,  18,  29, 220, 247, 129, 204, 362,
        241, 145, 173, 110, 320,  81, 268, 385, 312, 333, 347, 303, 324,
        357, 273,  54,  70,  94, 292, 366, 388, 231, 196,  30,  46, 109,
        132,  60, 397,  98, 153, 128, 192, 165, 115, 230, 262,  12, 291,
        253,  87,  62,   6,  38, 103, 225, 341, 306, 313, 311, 237, 195,
        266, 187, 133, 161,  35,   0,  73, 368, 369, 367, 285, 221,  91,
        392,  26, 213, 157, 212, 298, 305,   1, 226, 339, 164, 263, 217,
         68, 289,  13,  95, 258, 137, 386,  85, 160, 363, 242,  23, 141,
        327, 274, 317, 119, 177,  21, 296,   3, 202, 176,  72, 140,  86,
        162, 189, 134,  37,  45, 194,  16,  99, 127,  33,  24, 107, 169,
        283, 374, 261, 257, 315,  66,   9,  96], dtype=int64))

In [14]:
cars.loc["ford ranger"]

mpg              28.0
cylinders           4
displacement    120.0
horsepower       79.0
weight           2625
acceleration     18.6
model_year         82
origin            usa
Name: ford ranger, dtype: object

In [15]:
cars.loc[['mpg','weight']]

KeyError: "None of [Index(['mpg', 'weight'], dtype='object', name='name')] are in the [index]"

In [16]:
cars.reset_index(inplace = True)

In [17]:
cars

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
394,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevrolet s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [18]:
mpg = cars['mpg'].copy()

In [19]:
mpg.dtype

dtype('float64')

In [20]:
type(mpg)

pandas.core.series.Series

In [21]:
mpg.describe()

count    398.000000
mean      23.514573
std        7.815984
min        9.000000
25%       17.500000
50%       23.000000
75%       29.000000
max       46.600000
Name: mpg, dtype: float64

In [22]:
mpg.min()

9.0

In [23]:
mpg.max()

46.6

In [24]:
cars[cars.mpg == mpg.max()]

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
322,mazda glc,46.6,4,86.0,65.0,2110,17.9,80,japan

In [29]:
mpg.value_counts(normalize = True, sort = True)

mpg
13.0    0.050251
14.0    0.047739
18.0    0.042714
15.0    0.040201
26.0    0.035176
          ...
31.9    0.002513
16.9    0.002513
18.2    0.002513
22.3    0.002513
44.0    0.002513
Name: proportion, Length: 129, dtype: float64

In [27]:
cars

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
394,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevrolet s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [32]:
mpg.sort_values(ascending = False, inplace = True)

In [33]:
mpg

322    46.6
329    44.6
325    44.3
394    44.0
326    43.4
       ...
103    11.0
67     11.0
25     10.0
26     10.0
28      9.0
Name: mpg, Length: 398, dtype: float64

In [34]:
mpg.index

Index([322, 329, 325, 394, 326, 244, 309, 330, 324, 247,
       ...
        90,  42,  95, 124,  27, 103,  67,  25,  26,  28],
      dtype='int64', length=398)

In [35]:
mpg.sort_index(inplace = True)

In [36]:
mpg

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [37]:
lpk = (235.21/mpg).round(2)

In [38]:
lpk

0      13.07
1      15.68
2      13.07
3      14.70
4      13.84
       ...
393     8.71
394     5.35
395     7.35
396     8.40
397     7.59
Name: mpg, Length: 398, dtype: float64

In [41]:
lpk.describe()

count    398.000000
mean      11.212789
std        3.901407
min        5.050000
25%        8.110000
50%       10.230000
75%       13.440000
max       26.130000
Name: mpg, dtype: float64

In [42]:
origin = cars.origin.copy()

In [43]:
origin

0         usa
1         usa
2         usa
3         usa
4         usa
        ...
393       usa
394    europe
395       usa
396       usa
397       usa
Name: origin, Length: 398, dtype: object

In [44]:
origin.describe()

count     398
unique      3
top       usa
freq      249
Name: origin, dtype: object

In [45]:
import pandas as pd

In [46]:
cars = pd.read_csv('cars.csv')

In [47]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevrolet s-10

In [50]:
cars.index

RangeIndex(start=0, stop=398, step=1)

In [70]:
cars.set_index('name', inplace = True, drop = True)

In [67]:
cars.reset_index(inplace = True)

ValueError: cannot insert name, already exists

In [71]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
chevrolet s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [74]:
cars[cars.index.value_counts() > 1]

C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_31636\77052822.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cars[cars.index.value_counts() > 1]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,70,usa
chevrolet impala,14.0,8,454.0,220.0,4354,9.0,70,usa
plymouth fury iii,14.0,8,440.0,215.0,4312,8.5,70,usa
pontiac catalina,14.0,8,455.0,225.0,4425,10.0,70,usa
...,...,...,...,...,...,...,...,...
buick century,22.4,6,231.0,110.0,3415,15.8,81,usa
pontiac phoenix,27.0,4,151.0,90.0,2735,18.0,82,usa
honda accord,36.0,4,107.0,75.0,2205,14.5,82,japan
toyota corolla,34.0,4,108.0,70.0,2245,16.9,82,japan
honda civic,38.0,4,91.0,67.0,1965,15.0,82,japan

In [75]:
cars.index.value_counts(sort = True, ascending = False)

name
ford pinto             6
vw rabbit              5
ford maverick          5
toyota corolla         5
amc matador            5
                      ..
chevrolet monza 2+2    1
ford mustang ii        1
pontiac astro          1
amc pacer              1
chevrolet s-10         1
Name: count, Length: 300, dtype: int64

In [76]:
cars.index.name = 'car_model'

In [77]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
car_model,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
chevrolet s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [78]:
cars.reset_index(inplace = True)

In [79]:
cars

,car_model,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
394,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevrolet s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [80]:
cars.rename(columns = {'horsepower':'hp', 'origin':'country'}, inplace = True  )

In [81]:
cars

,car_model,mpg,cylinders,displacement,hp,weight,acceleration,model_year,country
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
394,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevrolet s-10,31.0,4,119.0,82.0,2720,19.4,82,usa